spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: crud

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root